plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'ai.rorsch.pandagenie.sdk.core'
    compileSdk 35

    defaultConfig {
        minSdk 24
        consumerProguardFiles 'consumer-rules.pro'
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = rootProject.findProperty('PANDAGENIE_SDK_GROUP') ?: 'ai.rorsch.pandagenie'
                artifactId = 'pandagenie-sdk-core'
                version = rootProject.findProperty('PANDAGENIE_SDK_VERSION') ?: '1.0.36'
            }
        }
    }
}
